CREATE TABLE agenda.contacto (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_completo VARCHAR(255),
  numero_documento VARCHAR(255),
  direccion VARCHAR(255),
  activo BOOLEAN NOT NULL,
  fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  fecha_modificacion TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE agenda.telefono (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contacto_id INTEGER REFERENCES agenda.contacto(id),
  numero_telefonico VARCHAR(20),
  activo BOOLEAN NOT NULL,
  fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  fecha_modificacion TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE agenda.correo (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contacto_id INTEGER REFERENCES agenda.contacto(id),
  email VARCHAR(255),
  activo BOOLEAN NOT NULL,
  fecha_creacion TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  fecha_modificacion TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Inserciones para la tabla 'contacto'
INSERT INTO agenda.contacto (nombre_completo, numero_documento, direccion, activo, fecha_creacion, fecha_modificacion) VALUES
('Juan Pérez', '12345678A', 'Calle Falsa 123, Ciudad', TRUE, '2023-01-01 10:00:00', '2023-01-02 11:00:00'),
('Ana Gómez', '87654321B', 'Avenida Siempre Viva 456, Ciudad', TRUE, '2023-01-03 12:00:00', '2023-01-04 13:00:00'),
('Luis Martínez', '11223344C', 'Plaza Mayor 789, Ciudad', FALSE, '2023-01-05 14:00:00', '2023-01-06 15:00:00');

-- Inserciones para la tabla 'telefono'
-- Asumiendo que los IDs de contacto van del 1 al 3
INSERT INTO agenda.telefono (contacto_id, numero_telefonico, activo, fecha_creacion, fecha_modificacion) VALUES
(1, '555-1234', TRUE, '2023-01-01 10:00:00', '2023-01-02 11:00:00'),
(1, '555-5678', FALSE, '2023-01-03 12:00:00', '2023-01-04 13:00:00'),
(2, '555-8765', TRUE, '2023-01-05 14:00:00', '2023-01-06 15:00:00'),
(3, '555-4321', TRUE, '2023-01-07 16:00:00', '2023-01-08 17:00:00');

-- Inserciones para la tabla 'correo'
-- Asumiendo que los IDs de contacto van del 1 al 3
INSERT INTO agenda.correo (contacto_id, email, activo, fecha_creacion, fecha_modificacion) VALUES
(1, 'juan.perez@example.com', TRUE, '2023-01-01 10:00:00', '2023-01-02 11:00:00'),
(1, 'jperez@example.com', FALSE, '2023-01-03 12:00:00', '2023-01-04 13:00:00'),
(2, 'ana.gomez@example.com', TRUE, '2023-01-05 14:00:00', '2023-01-06 15:00:00'),
(3, 'luis.martinez@example.com', TRUE, '2023-01-07 16:00:00', '2023-01-08 17:00:00');
